services:
  app:
    build: .
    container_name: onlineshop_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - onlineshop_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  webserver:
    image: nginx:alpine
    container_name: onlineshop_nginx
    ports:
      - "8002:80"   # onlineShop ni 8002 portga chiqaramiz
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - onlineshop_network

  db:
    image: mysql:8.0
    container_name: onlineshop_db
    restart: always
    environment:
      MYSQL_DATABASE: onlineshop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3309:3306" # onlineShop MySQL ni 3309 ga chiqaramiz
    networks:
      - onlineshop_network

networks:
  onlineshop_network:
    driver: bridge
